STAR \
--alignEndsType \
EndToEnd \
--genomeDir \
inputs/hg19_star_sjdb \
--genomeLoad \
NoSharedMemory \
--outBAMcompression \
10 \
--outFileNamePrefix \
outputs/ENCODE4.4020_CLIP1.umi.r1.fq.genome-mapped. \
--outFilterMultimapNmax \
1 \
--outFilterMultimapScoreRange \
1 \
--outFilterScoreMin \
10 \
--outFilterType \
BySJout \
--outReadsUnmapped \
Fastx \
--outSAMattrRGline \
ID:foo \
--outSAMattributes \
All \
--outSAMmode \
Full \
--outSAMtype \
BAM \
Unsorted \
--outSAMunmapped \
Within \
--outStd \
Log \
--readFilesIn \
inputs/ENCODE4.4020_CLIP1.umi.r1.fq.repeat-unmapped.sorted.fq \
--runMode \
alignReads \
--runThreadN \
8

STAR \
--alignEndsType \
EndToEnd \
--genomeDir \
inputs/hg19_star_sjdb \
--genomeLoad \
NoSharedMemory \
--outBAMcompression \
10 \
--outFileNamePrefix \
outputs/ENCODE4.4020_INPUT1.umi.r1.fq.genome-mapped. \
--outFilterMultimapNmax \
1 \
--outFilterMultimapScoreRange \
1 \
--outFilterScoreMin \
10 \
--outFilterType \
BySJout \
--outReadsUnmapped \
Fastx \
--outSAMattrRGline \
ID:foo \
--outSAMattributes \
All \
--outSAMmode \
Full \
--outSAMtype \
BAM \
Unsorted \
--outSAMunmapped \
Within \
--outStd \
Log \
--readFilesIn \
inputs/ENCODE4.4020_INPUT1.umi.r1.fq.repeat-unmapped.sorted.fq \
--runMode \
alignReads \
--runThreadN \
8
