#!/bin/bash

# Debugging settings:
#####################

# Print commands and their arguments as they are executed.
set -o xtrace

#Exit immediately if a command exits with a non-zero status.
# set -e

#the return value of a pipeline is the status of
#the last command to exit with a non-zero status,
#or zero if no command exited with a non-zero status
#set -o pipefail


#echo LD_LIBRARY_PATH: $LD_LIBRARY_PATH
#echo $(ls -l /opt/conda/lib/libpython2.7.so.1.0)
##################################################
#export LD_LIBRARY_PATH=/opt/conda/lib
##################################################
#echo LD_LIBRARY_PATH: $LD_LIBRARY_PATH
#echo $(ls -l /opt/conda/lib/libpython2.7.so.1.0)

#echo $(which cutadapt)
#echo $(which python)
#python --version


# gets -O argument (overlap_length) from content of file given in argument 2
OVERLAP_LENGTH=${2}
REMAINING_ARGS=${@:3}
cutadapt -O $(cat ${OVERLAP_LENGTH=}) ${REMAINING_ARGS}


set +x

