#!/bin/bash

# Debugging settings:
#####################

# Print commands and their arguments as they are executed.
set -x

# Exit immediately if a command exits with a non-zero status.
set -e

# the return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail




# command looks like this
#-------------------------
# samtoolsmmerge2     basename1  basename2  barcodeidA barcodeidB /long/path/basename1.bam /long/path/basename2.bam
#       $0                $1          $2      $3           $4               $5                   $6


# lets check it
echo "samtoolsmerge2 command line"
echo ${@}

echo merged basename precursors
echo $1
echo $2



# find common part between  both paired ends filenames, to define outFileNamePrefix parameter
#--------------------------------------------------------------------------------------------
MERGEDBASENAME=$(namemerge.sh $1 $2 "-")




if  [ "${3}" == "${4}" ]; then
  cp ${6} ${2}.bam
else
  samtools merge ${MERGEDBASENAME}Me.bam ${@:5}
fi
