#!/usr/bin/env bash

WD=${PWD}/results/intermediates



####### A01 #######
TESTSTEP=" demux CLIP1 reads for A01 barcode r1"
EXPECTED=10772
ACTUAL=`zcat ${WD}/KBP550.CLIP1.A01.r1.fq.gz | wc -l`

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

####### A01 #######
TESTSTEP=" demux CLIP1 reads for A01 barcode r2"
EXPECTED=10772
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.A01.r2.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### B06 #######
TESTSTEP=" demux CLIP1 reads for B06 barcode r1"
EXPECTED=10700
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.B06.r1.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi
####### B06  #######
TESTSTEP=" demux CLIP1 reads for B06 barcode r2"
EXPECTED=10700
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.B06.r2.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### C01 #######
TESTSTEP=" demux CLIP1 reads for C01 barcode r1"
EXPECTED=400
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.C01.r1.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

####### C01 #######
TESTSTEP=" demux CLIP1 reads for C01 barcode r2"
EXPECTED=400
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.C01.r2.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### D8f #######
TESTSTEP=" demux CLIP1 reads for D8f barcode r1"
EXPECTED=400
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.D8f.r1.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

####### D8f #######
TESTSTEP=" demux CLIP1 reads for D8f barcode r2"
EXPECTED=400
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.D8f.r2.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### X1A #######
TESTSTEP=" demux CLIP1 reads for X1A barcode r1"
EXPECTED=0
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.X1A.r1.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

####### X1A #######
TESTSTEP=" demux CLIP1 reads for X1A barcode r2"
EXPECTED=0
ACTUAL=$(zcat ${WD}/KBP550.CLIP1.X1A.r2.fq.gz | wc -l)

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

