#!/usr/bin/env bash

WD=${PWD}/results/intermediates



####### TESTING EXPECTED A01 READS MAPPED TO REP ELEMENT RRNA45 #######

TESTSTEP="rep-element (RRNA45) mapped clip1 read numbers for A01 barcode (Expected: ${EXPECTED})"
ACTUAL=`samtools view ${WD}/KBP550.clip1.A01.r-.fqTrTrMa.bam | grep RRNA45 | wc -l`
EXPECTED=204

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### TESTING EXPECTED B06 READS MAPPED TO REP ELEMENT RRNA45 #######

TESTSTEP="rep-element (RRNA45) mapped clip1 read numbers for B06 barcode (Expected: ${EXPECTED})"
ACTUAL=`samtools view ${WD}/KBP550.clip1.B06.r-.fqTrTrMa.bam | grep RRNA45 | wc -l`
EXPECTED=0

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### TESTING B06 EXPECTED UNMAPPED TO REPETITIVE READS INDIVIDUALLY #######
TESTSTEP="existance of read: (@TCTTG:SN1001:449:HGTN3ADXX:1:1101:6536:2619/1) in B06 unmapped mate1 fastq"
ACTUAL=`grep '@TCTTG:SN1001:449:HGTN3ADXX:1:1101:6536:2619/1' ${WD}/KBP550.clip1.B06.r-.fqTrTrU1.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

TESTSTEP="existence of read: (@TCTTG:SN1001:449:HGTN3ADXX:1:1101:6536:2619/2) in B06 unmapped mate2 fastq"
ACTUAL=`grep '@TCTTG:SN1001:449:HGTN3ADXX:1:1101:6536:2619/2' ${WD}/KBP550.clip1.B06.r-.fqTrTrU2.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi


TESTSTEP="existence of read: (@AAGCA:SN1001:449:HGTN3ADXX:2:2216:13087:100278/1) in B06 unmapped mate1 fastq"
EXPECTED=1
ACTUAL=`grep '@AAGCA:SN1001:449:HGTN3ADXX:2:2216:13087:100278/1' ${WD}/KBP550.clip1.B06.r-.fqTrTrU1.fq | wc -l`

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

TESTSTEP="existence of read: (@AAGCA:SN1001:449:HGTN3ADXX:2:2216:13087:100278/2) in B06 unmapped mate2 fastq"
ACTUAL=`grep '@AAGCA:SN1001:449:HGTN3ADXX:2:2216:13087:100278/2' ${WD}/KBP550.clip1.B06.r-.fqTrTrU2.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi



####### TESTING A01 EXPECTED UNMAPPED TO REPETITIVE READS INDIVIDUALLY #######

TESTSTEP="existence of read: (@CTAAG:SN1001:449:HGTN3ADXX:1:1101:7287:2422/1) in A01 unmapped mate1 fastq"
ACTUAL=`grep '@CTAAG:SN1001:449:HGTN3ADXX:1:1101:7287:2422/1' ${WD}/KBP550.clip1.A01.r-.fqTrTrU1.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

TESTSTEP="existence of read: (@CTAAG:SN1001:449:HGTN3ADXX:1:1101:7287:2422/2) in A01 unmapped mate2 fastq"
ACTUAL=`grep '@CTAAG:SN1001:449:HGTN3ADXX:1:1101:7287:2422/2' ${WD}/KBP550.clip1.A01.r-.fqTrTrU2.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

TESTSTEP="existence of read: (@TATGA:SN1001:449:HGTN3ADXX:2:2216:16149:91949/1) in A01 unmapped mate1 fastq"
ACTUAL=`grep '@TATGA:SN1001:449:HGTN3ADXX:2:2216:16149:91949/1' ${WD}/KBP550.clip1.A01.r-.fqTrTrU1.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

TESTSTEP="existence of read: (@TATGA:SN1001:449:HGTN3ADXX:2:2216:16149:91949/2) in A01 unmapped mate2 fastq"
ACTUAL=`grep '@TATGA:SN1001:449:HGTN3ADXX:2:2216:16149:91949/2' ${WD}/KBP550.clip1.A01.r-.fqTrTrU2.fq | wc -l`
EXPECTED=1

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

####### TESTING A01 EXPECTED MAPPED (NOT IN UNMAPPED.FQ) TO REPETITIVE READS INDIVIDUALLY #######

TESTSTEP="non-existence of read: (@TATGA:SN1001:449:HGTN3ADXX:2:2216:16149:91949/1) in A01 unmapped mate1 fastq"
ACTUAL=`grep 'CGATG:SN1001:449:HGTN3ADXX:1:1101:13050:16934/1' ${WD}/KBP550.clip1.A01.r-.fqTrTrU1.fq | wc -l`
EXPECTED=0

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi

TESTSTEP="non-existence of read: (@TATGA:SN1001:449:HGTN3ADXX:2:2216:16149:91949/2) in A01 unmapped mate2 fastq"
ACTUAL=`grep 'CGATG:SN1001:449:HGTN3ADXX:1:1101:13050:16934/2' ${WD}/KBP550.clip1.A01.r-.fqTrTrU2.fq | wc -l`
EXPECTED=0

if [ $EXPECTED -eq $ACTUAL ] ; then
    echo test $TESTSTEP SUCCEDED
else
    echo test $TESTSTEP FAILED
fi
