#!/usr/bin/env bash

# Debugging settings:
#####################
# exit immediately upon any error, output each line as it is executed
set -o errexit
set -o xtrace
set -o pipefail

#echo ${@}

pwd
ls -la


cp ${2#file://} ./$4

pwd
ls -la

