STAR \
--alignEndsType \
EndToEnd \
--genomeDir \
inputs/homo_sapiens_repbase_v2 \
--genomeLoad \
NoSharedMemory \
--outBAMcompression \
10 \
--outFileNamePrefix \
outputs/ENCODE4.4020_CLIP1.umi.r1.fqTrTr.sorted.STAR \
--outFilterMultimapNmax \
30 \
--outFilterMultimapScoreRange \
1 \
--outFilterScoreMin \
10 \
--outFilterType \
BySJout \
--outReadsUnmapped \
Fastx \
--outSAMattrRGline \
ID:foo \
--outSAMattributes \
All \
--outSAMmode \
Full \
--outSAMtype \
BAM \
Unsorted \
--outSAMunmapped \
Within \
--outStd \
Log \
--readFilesIn \
inputs/ENCODE4.4020_CLIP1.umi.r1.fqTrTr.sorted.fq \
--runMode \
alignReads \
--runThreadN \
8

STAR \
--alignEndsType \
EndToEnd \
--genomeDir \
inputs/homo_sapiens_repbase_v2 \
--genomeLoad \
NoSharedMemory \
--outBAMcompression \
10 \
--outFileNamePrefix \
outputs/ENCODE4.4020_INPUT1.umi.r1.fqTrTr.sorted.STAR \
--outFilterMultimapNmax \
30 \
--outFilterMultimapScoreRange \
1 \
--outFilterScoreMin \
10 \
--outFilterType \
BySJout \
--outReadsUnmapped \
Fastx \
--outSAMattrRGline \
ID:foo \
--outSAMattributes \
All \
--outSAMmode \
Full \
--outSAMtype \
BAM \
Unsorted \
--outSAMunmapped \
Within \
--outStd \
Log \
--readFilesIn \
inputs/ENCODE4.4020_INPUT1.umi.r1.fqTrTr.sorted.fq \
--runMode \
alignReads \
--runThreadN \
8
