#!/bin/bash

# Debugging settings:
#####################
# exit immediately upon any error, output each line as it is executed
set -ex -o pipefail

echo ${@}

touch ${12}.qc_fig.svg
touch ${12}.DistFig.svg
