cutadapt \
-O \
5 \
-f \
fastq \
--match-read-wildcards \
--times \
1 \
-e \
0.1 \
--quality-cutoff \
6 \
-m \
18 \
-o \
outputs/4020_CLIP1.umi.r1.fqTrTr.gz \
-a NNAGCGCTAGAGATC \
-a NAGCGCTAGAGATCG \
-a AGCGCTAGAGATCGG \
-a GCGCTAGAGATCGGA \
-a CGCTAGAGATCGGAA \
-a GCTAGAGATCGGAAG \
-a CTAGAGATCGGAAGA \
-a TAGAGATCGGAAGAG \
-a AGAGATCGGAAGAGC \
-a GAGATCGGAAGAGCA \
-a AGATCGGAAGAGCAC \
-a GATCGGAAGAGCACA \
-a ATCGGAAGAGCACAC \
-a TCGGAAGAGCACACG \
-a CGGAAGAGCACACGT \
-a GGAAGAGCACACGTC \
-a GAAGAGCACACGTCT \
-a AAGAGCACACGTCTG \
-a AGAGCACACGTCTGA \
-a GAGCACACGTCTGAA \
-a AGCACACGTCTGAAC \
-a GCACACGTCTGAACT \
-a CACACGTCTGAACTC \
-a ACACGTCTGAACTCC \
-a CACGTCTGAACTCCA \
-a ACGTCTGAACTCCAG \
-a CGTCTGAACTCCAGT \
-a GTCTGAACTCCAGTC \
-a TCTGAACTCCAGTCA \
inputs/4020_CLIP1.umi.r1.fqTr.gz > outputs/clip_metrics.txt
