cutadapt \
 -O \
 1 \
 -f \
 fastq \
 --match-read-wildcards \
 --times \
 1 \
 -e \
 0.1 \
 --quality-cutoff \
 6 \
 -m \
 18 \
 -o \
 outputs/4020_INPUT1.umi.r1.fqTr.gz \
-a NNAGGTGCGTAGATC \
-a NAGGTGCGTAGATCG \
-a AGGTGCGTAGATCGG \
-a GGTGCGTAGATCGGA \
-a GTGCGTAGATCGGAA \
-a TGCGTAGATCGGAAG \
-a GCGTAGATCGGAAGA \
-a CGTAGATCGGAAGAG \
-a GTAGATCGGAAGAGC \
-a TAGATCGGAAGAGCA \
-a AGATCGGAAGAGCAC \
-a GATCGGAAGAGCACA \
-a ATCGGAAGAGCACAC \
-a TCGGAAGAGCACACG \
-a CGGAAGAGCACACGT \
-a GGAAGAGCACACGTC \
-a GAAGAGCACACGTCT \
-a AAGAGCACACGTCTG \
-a AGAGCACACGTCTGA \
-a GAGCACACGTCTGAA \
-a AGCACACGTCTGAAC \
-a GCACACGTCTGAACT \
-a CACACGTCTGAACTC \
-a ACACGTCTGAACTCC \
-a CACGTCTGAACTCCA \
-a ACGTCTGAACTCCAG \
-a CGTCTGAACTCCAGT \
-a GTCTGAACTCCAGTC \
-a TCTGAACTCCAGTCA \
 inputs/4020_INPUT1.umi.r1.fq.gz > outputs/input_metrics.txt
